# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Text Image Editable"
  description:
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: Insert heading here
    description_html: Lorem ipsum lorem ipsum lorem ipsum
    include_image: True
    image_position: Right
    image: https://r2-storage.inosida.workers.dev/placeholderimage.png
    alt: Image description
    include_button: True
    button:
      text: Button text
      link: /
      custom_background_color: False
      background_color: 'black'
  style:
    content_alignment: Left
    vertical_alignment: Top
    custom_background_color: false
    background_color: '#f5f5f5'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  vertical_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_vertical_top
          name: Top
        - icon: align_vertical_center
          name: Middle
        - icon: align_vertical_bottom
          name: Bottom
  content_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_horizontal_left
          name: Left
        - icon: align_horizontal_center
          name: Center
        - icon: align_horizontal_right
          name: Right
  custom_background_color:
    type: switch
  background_color:
    type: color
    hidden: "!custom_background_color"
  include_image:
    type: switch
  image:
    type: image
    hidden: "!include_image"
  image_position:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_horizontal_left
          name: Left
        - icon: align_horizontal_right
          name: Right
    hidden: "!include_image"
  alt:
    type: text
    hidden: "!include_image"
  include_button:
    type: switch
  button:
    hidden: "!include_button"